DATA:
  CLASS_NAME_FILE: 'configs/namefiles/coco80.names'
  AUGMENT: 1

  TRAIN:
    IMG_DIR: 'data/INRIAPerson/Train/pos'
    LAB_DIR:

DETECTOR:
  NAME: ["YOLOV2"]
  INPUT_SIZE: [416, 416]
  BATCH_SIZE: 8
  MODEL_CONFIG: 'HHDet/yolov2/yolov2/config/yolo.cfg'
  CONF_THRESH: 0.5
  IOU_THRESH: 0.45

  # yolov2: no residual blocks
  PERTURB:
    GATE: null

ATTACKER:
  METHOD: "optim"
  EPSILON: 255
  MAX_EPOCH: 1000
  ITER_STEP: 1
  STEP_LR: 0.03
  ATTACK_CLASS: '0'
  LOSS_FUNC: "obj-tv"
  tv_eta: 2.5

  LR_SCHEDULER: 'ALRS'


  PATCH:
    WIDTH: 300
    HEIGHT: 300
    SCALE: 0.15
    INIT: "gray"

    TRANSFORM: ['jitter', 'rotate', 'median_pool', 'cutout']